DOMAIN_CHOICES = [
    ('Business Intelligence', 'Business Intelligence'),
    ('Extract Transform Load', 'Extract Transform Load'),
    ('Data Integration', 'Data Integration'),
    ('Data Marketing', 'Data Marketing'),
    ('Data Governance', 'Data Governance'),
    ('Machine Learning', 'Machine Learning'),
    ('Data Analytics', 'Data Analytics'),
    ('Data Virtualization', 'Data Virtualization'),
    ('Advanced Analytics', 'Advanced Analytics'),
    ('Master Data Management', 'Master Data Management'),
    ('Reverse ETL', 'Reverse ETL'),
    ('Data Security', 'Data Security'),
    ('Data Monitoring', 'Data Monitoring'),
    ('Data Observability', 'Data Observability'),
    ('Spatial Analytics', 'Spatial Analytics'),
    ('Data Quality', 'Data Quality'),
    ('Customer Data Platform', 'Customer Data Platform'),
    ('Marketing Analytics', 'Marketing Analytics'),
    ('Data Activation', 'Data Activation'),
    ('Behavioural Data Platform', 'Behavioural Data Platform'),
    ('Graph Database', 'Graph Database'),
    ('Data Modeler', 'Data Modeler'),
    ('Data API', 'Data API'),
    ('Mobile First BI', 'Mobile First BI'),
    ('Data App Development', 'Data App Development'),
    ('Deep Data Observability', 'Deep Data Observability'),
    ('FinOps', 'FinOps'),
    ('DataOps', 'DataOps'),
    ('Real Time ETL', 'Real Time ETL'),
    ('Product Analytics Platform', 'Product Analytics Platform'),
    ('Synthetic Data Generation', 'Synthetic Data Generation'),
    ('Data Visualization', 'Data Visualization'),
    ('Artificial Intelligence', 'Artificial Intelligence'),
    ('Generative AI', 'Generative AI'),
    ('Automation', 'Automation'),
]